 
version: "3.8"

services:
  db:
    image: mysql:latest
    environment:
  #not use in release env
      MYSQL_ROOT_PASSWORD: password  # Replace with your desired password (store securely)
      MYSQL_DATABASE: data        # Replace with your desired database name
      MYSQL_USER: dcard                 # Replace with your desired username
      MYSQL_PASSWORD: i_love_dcard          # Replace with your desired password for the user
    # Adjust port mapping as needed
    ports:
      - "3306:3306"
    # Mount the init script as a volume (optional)
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Uncomment if using init.sql
    # Persistent data volume (uncomment and adjust)

      - db-data:/var/lib/mysql
    restart: unless-stopped  # Restart container on failures
  redis:
    image: redis:alpine
    restart: unless-stopped  # Restart container on failures

    ports:
      - "6379:6379"
  go-api:
    build: .
    restart: unless-stopped  # Restart container on failures

    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080 (adjust as needed)
  #   networks:
  #     # - default  # Connect to the default Docker network
      
  #     network_mode: "host"

      


# networks:
#   default:
#     external: true  # Allow containers to access the host machine as localhost

# Replace paths with your actual file locations (if using init.sql)
volumes:
  # Optional volume to store persistent data (uncomment if needed)
  db-data: {}
  