-- Create the Ads table with min_age and max_age (default values)
CREATE TABLE Ads (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  start_at DATETIME NOT NULL,
  end_at DATETIME NOT NULL,
  min_age INT DEFAULT 1,  -- Default minimum age (1)
  max_age INT DEFAULT 100 -- Default maximum age (100)
--   FOREIGN KEY (id) REFERENCES AdConditions(ad_id)  -- Optional foreign key for future reference
);

-- Create the Conditions table for non-age targeting options
CREATE TABLE Conditions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  type ENUM('gender', 'country', 'platform')  NOT NULL,
  value VARCHAR(255) DEFAULT NULL
);

-- Create the AdConditions table for linking ads and conditions
CREATE TABLE AdConditions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  ad_id INT NOT NULL,
  condition_id INT NOT NULL,
  FOREIGN KEY (ad_id) REFERENCES Ads(id),
  FOREIGN KEY (condition_id) REFERENCES Conditions(id)
);

-- Add indexes for efficient querying (recommended)
ALTER TABLE Ads ADD INDEX (start_at, end_at);
ALTER TABLE Conditions ADD INDEX (type);

-- Insert gender conditions
INSERT INTO Conditions (type, value) VALUES ('gender', 'M');
INSERT INTO Conditions (type, value) VALUES ('gender', 'F');


-- Insert platform conditions
INSERT INTO Conditions (type, value) VALUES ('platform', 'android');
INSERT INTO Conditions (type, value) VALUES ('platform', 'ios');
INSERT INTO Conditions (type, value) VALUES ('platform', 'web');


-- Insert country conditions
INSERT INTO Conditions (type, value) VALUES ('country', 'ALL');
 
INSERT INTO Conditions (type, value)
SELECT 'country', code
FROM (
  SELECT '' AS code UNION ALL
  SELECT 'AF' AS code UNION ALL
  SELECT 'AX' AS code UNION ALL
  SELECT 'AL' AS code UNION ALL
  SELECT 'DZ' AS code UNION ALL
  SELECT 'AS' AS code UNION ALL
  SELECT 'AD' AS code UNION ALL
  SELECT 'AO' AS code UNION ALL
  SELECT 'AI' AS code UNION ALL
  SELECT 'AQ' AS code UNION ALL
  SELECT 'AG' AS code UNION ALL
  SELECT 'AR' AS code UNION ALL
  SELECT 'AM' AS code UNION ALL
  SELECT 'AW' AS code UNION ALL
  SELECT 'AU' AS code UNION ALL
  SELECT 'AT' AS code UNION ALL
  SELECT 'AZ' AS code UNION ALL
  SELECT 'BS' AS code UNION ALL
  SELECT 'BH' AS code UNION ALL
  SELECT 'BD' AS code UNION ALL
  SELECT 'BB' AS code UNION ALL
  SELECT 'BY' AS code UNION ALL
  SELECT 'BE' AS code UNION ALL
  SELECT 'BZ' AS code UNION ALL
  SELECT 'BJ' AS code UNION ALL
  SELECT 'BM' AS code UNION ALL
  SELECT 'BT' AS code UNION ALL
  SELECT 'BO' AS code UNION ALL
  SELECT 'BQ' AS code UNION ALL
  SELECT 'BA' AS code UNION ALL
  SELECT 'BW' AS code UNION ALL
  SELECT 'BV' AS code UNION ALL
  SELECT 'BR' AS code UNION ALL
  SELECT 'IO' AS code UNION ALL
  SELECT 'BN' AS code UNION ALL
  SELECT 'BG' AS code UNION ALL
  SELECT 'BF' AS code UNION ALL
  SELECT 'BI' AS code UNION ALL
  SELECT 'CV' AS code UNION ALL
  SELECT 'KH' AS code UNION ALL
  SELECT 'CM' AS code UNION ALL
  SELECT 'CA' AS code UNION ALL
  SELECT 'KY' AS code UNION ALL
  SELECT 'CF' AS code UNION ALL
  SELECT 'TD' AS code UNION ALL
  SELECT 'CL' AS code UNION ALL
  SELECT 'CN' AS code UNION ALL
  SELECT 'CX' AS code UNION ALL
  SELECT 'CC' AS code UNION ALL
  SELECT 'CO' AS code UNION ALL
  SELECT 'KM' AS code UNION ALL
  SELECT 'CG' AS code UNION ALL
  SELECT 'CD' AS code UNION ALL
  SELECT 'CK' AS code UNION ALL
  SELECT 'CR' AS code UNION ALL
  SELECT 'CI' AS code UNION ALL
  SELECT 'HR' AS code UNION ALL
  SELECT 'CU' AS code UNION ALL
  SELECT 'CW' AS code UNION ALL
  SELECT 'CY' AS code UNION ALL
  SELECT 'CZ' AS code UNION ALL
  SELECT 'DK' AS code UNION ALL
  SELECT 'DJ' AS code UNION ALL
  SELECT 'DM' AS code UNION ALL
  SELECT 'DO' AS code UNION ALL
  SELECT 'EC' AS code UNION ALL
  SELECT 'EG' AS code UNION ALL
  SELECT 'SV' AS code UNION ALL
  SELECT 'GQ' AS code UNION ALL
  SELECT 'ER' AS code UNION ALL
  SELECT 'EE' AS code UNION ALL
  SELECT 'SZ' AS code UNION ALL
  SELECT 'ET' AS code UNION ALL
  SELECT 'FK' AS code UNION ALL
  SELECT 'FO' AS code UNION ALL
  SELECT 'FJ' AS code UNION ALL
  SELECT 'FI' AS code UNION ALL
  SELECT 'FR' AS code UNION ALL
  SELECT 'GF' AS code UNION ALL
  SELECT 'PF' AS code UNION ALL
  SELECT 'TF' AS code UNION ALL
  SELECT 'GA' AS code UNION ALL
  SELECT 'GM' AS code UNION ALL
  SELECT 'GE' AS code UNION ALL
  SELECT 'DE' AS code UNION ALL
  SELECT 'GH' AS code UNION ALL
  SELECT 'GI' AS code UNION ALL
  SELECT 'GR' AS code UNION ALL
  SELECT 'GL' AS code UNION ALL
  SELECT 'GD' AS code UNION ALL
  SELECT 'GP' AS code UNION ALL
  SELECT 'GU' AS code UNION ALL
  SELECT 'GT' AS code UNION ALL
  SELECT 'GG' AS code UNION ALL
  SELECT 'GN' AS code UNION ALL
  SELECT 'GW' AS code UNION ALL
  SELECT 'GY' AS code UNION ALL
  SELECT 'HT' AS code UNION ALL
  SELECT 'HM' AS code UNION ALL
  SELECT 'VA' AS code UNION ALL
  SELECT 'HN' AS code UNION ALL
  SELECT 'HK' AS code UNION ALL
  SELECT 'HU' AS code UNION ALL
  SELECT 'IS' AS code UNION ALL
  SELECT 'IN' AS code UNION ALL
  SELECT 'ID' AS code UNION ALL
  SELECT 'IR' AS code UNION ALL
  SELECT 'IQ' AS code UNION ALL
  SELECT 'IE' AS code UNION ALL
  SELECT 'IM' AS code UNION ALL
  SELECT 'IL' AS code UNION ALL
  SELECT 'IT' AS code UNION ALL
  SELECT 'JM' AS code UNION ALL
  SELECT 'JP' AS code UNION ALL
  SELECT 'JE' AS code UNION ALL
  SELECT 'JO' AS code UNION ALL
  SELECT 'KZ' AS code UNION ALL
  SELECT 'KE' AS code UNION ALL
  SELECT 'KI' AS code UNION ALL
  SELECT 'KP' AS code UNION ALL
  SELECT 'KR' AS code UNION ALL
  SELECT 'KW' AS code UNION ALL
  SELECT 'KG' AS code UNION ALL
  SELECT 'LA' AS code UNION ALL
  SELECT 'LV' AS code UNION ALL
  SELECT 'LB' AS code UNION ALL
  SELECT 'LS' AS code UNION ALL
  SELECT 'LR' AS code UNION ALL
  SELECT 'LY' AS code UNION ALL
  SELECT 'LI' AS code UNION ALL
  SELECT 'LT' AS code UNION ALL
  SELECT 'LU' AS code UNION ALL
  SELECT 'MO' AS code UNION ALL
  SELECT 'MG' AS code UNION ALL
  SELECT 'MW' AS code UNION ALL
  SELECT 'MY' AS code UNION ALL
  SELECT 'MV' AS code UNION ALL
  SELECT 'ML' AS code UNION ALL
  SELECT 'MT' AS code UNION ALL
  SELECT 'MH' AS code UNION ALL
  SELECT 'MQ' AS code UNION ALL
  SELECT 'MR' AS code UNION ALL
  SELECT 'MU' AS code UNION ALL
  SELECT 'YT' AS code UNION ALL
  SELECT 'MX' AS code UNION ALL
  SELECT 'FM' AS code UNION ALL
  SELECT 'MD' AS code UNION ALL
  SELECT 'MC' AS code UNION ALL
  SELECT 'MN' AS code UNION ALL
  SELECT 'ME' AS code UNION ALL
  SELECT 'MS' AS code UNION ALL
  SELECT 'MA' AS code UNION ALL
  SELECT 'MZ' AS code UNION ALL
  SELECT 'MM' AS code UNION ALL
  SELECT 'NA' AS code UNION ALL
  SELECT 'NR' AS code UNION ALL
  SELECT 'NP' AS code UNION ALL
  SELECT 'NL' AS code UNION ALL
  SELECT 'NC' AS code UNION ALL
  SELECT 'NZ' AS code UNION ALL
  SELECT 'NI' AS code UNION ALL
  SELECT 'NE' AS code UNION ALL
  SELECT 'NG' AS code UNION ALL
  SELECT 'NU' AS code UNION ALL
  SELECT 'NF' AS code UNION ALL
  SELECT 'MK' AS code UNION ALL
  SELECT 'MP' AS code UNION ALL
  SELECT 'NO' AS code UNION ALL
  SELECT 'OM' AS code UNION ALL
  SELECT 'PK' AS code UNION ALL
  SELECT 'PW' AS code UNION ALL
  SELECT 'PS' AS code UNION ALL
  SELECT 'PA' AS code UNION ALL
  SELECT 'PG' AS code UNION ALL
  SELECT 'PY' AS code UNION ALL
  SELECT 'PE' AS code UNION ALL
  SELECT 'PH' AS code UNION ALL
  SELECT 'PN' AS code UNION ALL
  SELECT 'PL' AS code UNION ALL
  SELECT 'PT' AS code UNION ALL
  SELECT 'PR' AS code UNION ALL
  SELECT 'QA' AS code UNION ALL
  SELECT 'RE' AS code UNION ALL
  SELECT 'RO' AS code UNION ALL
  SELECT 'RU' AS code UNION ALL
  SELECT 'RW' AS code UNION ALL
  SELECT 'BL' AS code UNION ALL
  SELECT 'SH' AS code UNION ALL
  SELECT 'KN' AS code UNION ALL
  SELECT 'LC' AS code UNION ALL
  SELECT 'MF' AS code UNION ALL
  SELECT 'PM' AS code UNION ALL
  SELECT 'VC' AS code UNION ALL
  SELECT 'WS' AS code UNION ALL
  SELECT 'SM' AS code UNION ALL
  SELECT 'ST' AS code UNION ALL
  SELECT 'SA' AS code UNION ALL
  SELECT 'SN' AS code UNION ALL
  SELECT 'RS' AS code UNION ALL
  SELECT 'SC' AS code UNION ALL
  SELECT 'SL' AS code UNION ALL
  SELECT 'SG' AS code UNION ALL
  SELECT 'SX' AS code UNION ALL
  SELECT 'SK' AS code UNION ALL
  SELECT 'SI' AS code UNION ALL
  SELECT 'SB' AS code UNION ALL
  SELECT 'SO' AS code UNION ALL
  SELECT 'ZA' AS code UNION ALL
  SELECT 'GS' AS code UNION ALL
  SELECT 'SS' AS code UNION ALL
  SELECT 'ES' AS code UNION ALL
  SELECT 'LK' AS code UNION ALL
  SELECT 'SD' AS code UNION ALL
  SELECT 'SR' AS code UNION ALL
  SELECT 'SJ' AS code UNION ALL
  SELECT 'SE' AS code UNION ALL
  SELECT 'CH' AS code UNION ALL
  SELECT 'SY' AS code UNION ALL
  SELECT 'TW' AS code UNION ALL
  SELECT 'TJ' AS code UNION ALL
  SELECT 'TZ' AS code UNION ALL
  SELECT 'TH' AS code UNION ALL
  SELECT 'TL' AS code UNION ALL
  SELECT 'TG' AS code UNION ALL
  SELECT 'TK' AS code UNION ALL
  SELECT 'TO' AS code UNION ALL
  SELECT 'TT' AS code UNION ALL
  SELECT 'TN' AS code UNION ALL
  SELECT 'TR' AS code UNION ALL
  SELECT 'TM' AS code UNION ALL
  SELECT 'TC' AS code UNION ALL
  SELECT 'TV' AS code UNION ALL
  SELECT 'UG' AS code UNION ALL
  SELECT 'UA' AS code UNION ALL
  SELECT 'AE' AS code UNION ALL
  SELECT 'GB' AS code UNION ALL
  SELECT 'US' AS code UNION ALL
  SELECT 'UM' AS code UNION ALL
  SELECT 'UY' AS code UNION ALL
  SELECT 'UZ' AS code UNION ALL
  SELECT 'VU' AS code UNION ALL
  SELECT 'VE' AS code UNION ALL
  SELECT 'VN' AS code UNION ALL
  SELECT 'VG' AS code UNION ALL
  SELECT 'VI' AS code UNION ALL
  SELECT 'WF' AS code UNION ALL
  SELECT 'EH' AS code UNION ALL
  SELECT 'YE' AS code UNION ALL
  SELECT 'ZM' AS code UNION ALL
  SELECT 'ZW' AS cod) AS codes;